train:
  epochs: 25
  lr: 0.0001
  batch_size: 1024
  seq_len: 50
  grad_clip: inf
model:
  name: 'mirnn' # lstmpt, cprnn, 2rnn
  input_size: 200
  hidden_size: 2048
  rank: 64
  dropout: 0
data:
  path: 'data/processed/ptb' # Path to the data
eval:
  path: "runs/ptb/mirnn_e100_l001_b1024_s100_r64"


# Options for data paths:
#   data/processed/anna
#   data/processed/ptb
