runs: 1
train:
  epochs: 300
  lr: 0.001 #0.0001 #0.001
  threshold : 0.02
  factor : 0.1 #0.02
  patience : 2
  batch_size: 128
  seq_len: 50 #150
  grad_clip: inf
  hpopt: False
  verbose: False
model:
  name: mirnn #2rnn, cprnn, mirnnnew, lstmpt
  input_size: 0
  hidden_size: 2048
  rank: 1
  dropout: 0
  gate: tanh # tanh, sigmoid, identity
data:
  path: data/processed/ptb # Path to the data
  tokenizer: char # char, word
  output : /network/scratch/l/lizairem/cprnn/runs/exp_c_hp
#  output: runs
eval:
  path: 'runs/ptb/e25_l0.0001_b1024_s50_ginf_ncprnn_i200_h2048_r64_d0'

# Options for data paths:
#   data/processed/anna
#   data/processed/ptb

# Experiments
# e25_l0.0001_b1024_s50_ginf_nmirnn_i200_h2048_r64_d0
# e25_l0.0001_b1024_s50_ginf_ncprnn_i200_h2048_r64_d0
