# ===================================================================================================
# PTB Dataset
# ===================================================================================================

## 1. BPC vs. Params (All models)
#visualization:
#  experiments: /home/mila/m/marawan.gamal/projects/cp-rnn/runs/ptb
#  output: /home/mila/m/marawan.gamal/projects/cp-rnn/figures/ptb_bpc_vs_params.png
#  plt_type: scatter # scatter, plot, errorbar
#  group_by: ["model.name"]
#  min_epochs: 24
#  min_trials: 3
#runs: any
#train:
#  epochs: 25
#  lr: 0.0001
#  batch_size: 128
#  seq_len: 50
#  grad_clip: inf
#  hpopt: any
#  verbose: any
#model:
#  name: any # lstmpt, cprnn, 2rnn, 'mirnn'
#  input_size: any
#  hidden_size: any
#  rank: any
#  dropout: 0
#  gate: tanh # tanh, sigmoid, identity
#data:
#  path: any # Path to the data
#  tokenizer: char # char, word
#  output: any
#eval:
#  compute_grads: any
#  path: any


# 2. BPC vs. Params (CPRNNs only)
visualization:
  experiments: /home/mila/m/marawan.gamal/projects/cp-rnn/runs/ptb
  output: /home/mila/m/marawan.gamal/projects/cp-rnn/figures/ptb_cprnn_bpc_vs_params.png
  plt_type: plot # scatter, plot
  group_by: [ "model.hidden_size" ]
  min_epochs: 24
  min_trials: 3
runs: any
train:
  epochs: 25
  lr: 0.0001
  batch_size: 128
  seq_len: 50
  grad_clip: inf
  hpopt: any
  verbose: any
model:
  name: cprnn # lstmpt, cprnn, 2rnn, 'mirnn'
  input_size: any
  hidden_size: any
  rank: any
  dropout: 0
  gate: tanh # tanh, sigmoid, identity
data:
  path: any # Path to the data
  tokenizer: char # char, word
  output: any
eval:
  compute_grads: any
  path: any

# ===================================================================================================
# ANNA Dataset
# ===================================================================================================

## 1. BPC vs. Params (All models)
#visualization:
#  experiments: /home/mila/m/marawan.gamal/projects/cp-rnn/runs/anna
#  output: /home/mila/m/marawan.gamal/projects/cp-rnn/figures/anna_bpc_vs_params.png
#  plt_type: scatter # scatter, plot, errorbar
#  group_by: ["model.name"]
#  min_epochs: 24
#  min_trials: 3
#runs: any
#train:
#  epochs: 25
#  lr: 0.0001
#  batch_size: 128
#  seq_len: 50
#  grad_clip: inf
#  hpopt: any
#  verbose: any
#model:
#  name: any # lstmpt, cprnn, 2rnn, 'mirnn'
#  input_size: any
#  hidden_size: any
#  rank: any
#  dropout: 0
#  gate: tanh # tanh, sigmoid, identity
#data:
#  path: any # Path to the data
#  tokenizer: char # char, word
#  output: any
#eval:
#  compute_grads: any
#  path: any

## 2. BPC vs. Params (CPRNNs only)
#visualization:
#  experiments: /home/mila/m/marawan.gamal/projects/cp-rnn/runs/anna
#  output: /home/mila/m/marawan.gamal/projects/cp-rnn/figures/anna_cprnn_bpc_vs_params.png
#  plt_type: plot # scatter, plot, errorbar
#  group_by: [ "model.hidden_size" ]
#  min_epochs: 24
#  min_trials: 3
#runs: any
#train:
#  epochs: 25
#  lr: 0.0001
#  batch_size: 128
#  seq_len: 50
#  grad_clip: inf
#  hpopt: any
#  verbose: any
#model:
#  name: cprnn # lstmpt, cprnn, 2rnn, 'mirnn'
#  input_size: any
#  hidden_size: any
#  rank: any
#  dropout: 0
#  gate: tanh # tanh, sigmoid, identity
#data:
#  path: any # Path to the data
#  tokenizer: char # char, word
#  output: any
#eval:
#  compute_grads: any
#  path: any